### ISSUE TITLE
Issue with WebM Format Token Usage

### ISSUE THREAD

**Issue by brunocalado** [xaukael/card-tokens#16]
I'm encountering an issue when attempting to use the WebM format as tokens in Foundry VTT. While this format is functional when used as a token, I've encountered an error when utilizing it with your module. The error message is as follows:
![image](https://github.com/xaukael/card-tokens/assets/4999783/8151a25f-e1b1-4806-b172-8f773b1d12a5)
![image](https://github.com/xaukael/card-tokens/assets/4999783/9c2bbcd0-d99c-4f53-ba88-bb3b2fff8e5a)

I appreciate your assistance in resolving this matter. If there's any additional information needed from my end to diagnose and address the issue, please let me know.

Thank you for your attention to this matter.

Best regards,

**Comment by xaukael** [comment]
As well as I can tell, the issue is that actors, and apparently cards as well by the look of your deck sheet, do not allow webm for an image source. Tokens do, I suppose, but there is not really a readily apparent option to set a separate image for the token. I would have to create a flag for every card for a webm (and expect users to fill each flag) if I were to even attempt to support such a thing. This is more a issue with core foundry than it is a flaw in card-tokens.
